import shutil
import glob

def delete_checkpoints(run_dir: str):
    """
    Deletes unecessary checkpoints generated by HuggingFace `Trainer`
    Args:
        run_dir (str): output directory where artifacts are saved
    """

    for file in glob.glob(f"{run_dir}/checkpoint-*"):
        shutil.rmtree(file, ignore_errors=True)